// <auto-generated />
using System;
using BackEndWaterFloodApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace project.Migrations
{
    [DbContext(typeof(WaterfloodDbContext))]
    [Migration("20260831205713_WaterfloodInitialSchema")]
    partial class WaterfloodInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndWaterFloodApp.Domain.Entities.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxInjectionPressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaxWaterCutPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinInjectionRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MinOilProductionRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlertThresholds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            MaxInjectionPressure = 2500m,
                            MaxWaterCutPercent = 80m,
                            MinInjectionRate = 1000m,
                            MinOilProductionRate = 500m
                        });
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Domain.Entities.InjectorProducerRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Distance")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("InjectorWellId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProducerWellId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipStatusCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InjectorWellId");

                    b.HasIndex("ProducerWellId");

                    b.HasIndex("RelationshipStatusCode");

                    b.ToTable("InjectorProducerRelationships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.4m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000001"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-000000000002"),
                            RelationshipStatusCode = "ACT"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.8m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000001"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-000000000003"),
                            RelationshipStatusCode = "ACT"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.5m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000004"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-000000000005"),
                            RelationshipStatusCode = "ACT"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.9m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000004"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-000000000006"),
                            RelationshipStatusCode = "ACT"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.6m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000007"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-000000000008"),
                            RelationshipStatusCode = "ACT"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Distance = 0.7m,
                            InjectorWellId = new Guid("a1000001-0000-0000-0000-000000000009"),
                            ProducerWellId = new Guid("a1000001-0000-0000-0000-00000000000a"),
                            RelationshipStatusCode = "ACT"
                        });
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Domain.Entities.WaterfloodRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("InjectionPressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("InjectionRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("OilProductionRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("WaterCut")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WaterProductionRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("WellName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WellStatusCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("WellTypeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("FieldName");

                    b.HasIndex("MeasurementDate");

                    b.HasIndex("WellName")
                        .IsUnique();

                    b.HasIndex("WellStatusCode");

                    b.HasIndex("WellTypeCode");

                    b.ToTable("WaterfloodRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "North Field",
                            InjectionPressure = 2100m,
                            InjectionRate = 4500m,
                            Latitude = 22.12346m,
                            Longitude = 56.123456m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WellName = "INJ-101",
                            WellStatusCode = "ACT",
                            WellTypeCode = "INJ"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "North Field",
                            Latitude = 22.12510m,
                            Longitude = 56.126200m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 1200m,
                            WaterCut = 40m,
                            WaterProductionRate = 800m,
                            WellName = "PROD-201",
                            WellStatusCode = "ACT",
                            WellTypeCode = "PROD"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "North Field",
                            Latitude = 22.12820m,
                            Longitude = 56.129300m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 650m,
                            WaterCut = 74m,
                            WaterProductionRate = 1850m,
                            WellName = "PROD-202",
                            WellStatusCode = "ACT",
                            WellTypeCode = "PROD"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "Central Field",
                            InjectionPressure = 1950m,
                            InjectionRate = 3800m,
                            Latitude = 21.98765m,
                            Longitude = 55.987654m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WellName = "INJ-102",
                            WellStatusCode = "ACT",
                            WellTypeCode = "INJ"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "Central Field",
                            Latitude = 21.99010m,
                            Longitude = 55.990200m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 900m,
                            WaterCut = 55m,
                            WaterProductionRate = 1100m,
                            WellName = "PROD-203",
                            WellStatusCode = "ACT",
                            WellTypeCode = "PROD"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "Central Field",
                            Latitude = 21.99320m,
                            Longitude = 55.994100m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 400m,
                            WaterCut = 84m,
                            WaterProductionRate = 2100m,
                            WellName = "PROD-204",
                            WellStatusCode = "ACT",
                            WellTypeCode = "PROD"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "South Field",
                            InjectionPressure = 2400m,
                            InjectionRate = 2500m,
                            Latitude = 20.65432m,
                            Longitude = 54.654321m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WellName = "INJ-103",
                            WellStatusCode = "MNT",
                            WellTypeCode = "INJ"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "South Field",
                            Latitude = 20.65710m,
                            Longitude = 54.658200m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 1500m,
                            WaterCut = 25m,
                            WaterProductionRate = 500m,
                            WellName = "PROD-205",
                            WellStatusCode = "ACT",
                            WellTypeCode = "PROD"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "West Field",
                            InjectionPressure = 2650m,
                            InjectionRate = 1800m,
                            Latitude = 23.45679m,
                            Longitude = 57.123456m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WellName = "INJ-104",
                            WellStatusCode = "ACT",
                            WellTypeCode = "INJ"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            FieldName = "West Field",
                            Latitude = 23.45920m,
                            Longitude = 57.126100m,
                            MeasurementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OilProductionRate = 300m,
                            WaterCut = 90m,
                            WaterProductionRate = 2700m,
                            WellName = "PROD-206",
                            WellStatusCode = "SHT",
                            WellTypeCode = "PROD"
                        });
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("zRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleID");

                    b.HasIndex("UserID");

                    b.HasIndex("zRoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Models.zsk.zRole", b =>
                {
                    b.Property<int>("zRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("zRoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("zRoleID");

                    b.ToTable("zRoles");

                    b.HasData(
                        new
                        {
                            zRoleID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            zRoleID = 2,
                            Name = "Operator"
                        },
                        new
                        {
                            zRoleID = 3,
                            Name = "PetroleumEngineer"
                        });
                });

            modelBuilder.Entity("ZSK.Services.ReferenceData.Entities.ZskRefMonitoringRule", b =>
                {
                    b.Property<string>("RuleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("DefaultThresholdValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetWellType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("RuleCode");

                    b.ToTable("ZSK_Ref_MonitoringRules");

                    b.HasData(
                        new
                        {
                            RuleCode = "RULE_HIGH_WATER_CUT",
                            DefaultThresholdValue = 80.0m,
                            Description = "Producer water cut exceeds defined threshold",
                            Name = "High Water Cut",
                            Severity = "Warning",
                            TargetWellType = "PROD"
                        },
                        new
                        {
                            RuleCode = "RULE_LOW_OIL_PROD",
                            DefaultThresholdValue = 500.0m,
                            Description = "Oil production falls below defined threshold",
                            Name = "Low Oil Production",
                            Severity = "Warning",
                            TargetWellType = "PROD"
                        },
                        new
                        {
                            RuleCode = "RULE_COMBINED_DEFICIT",
                            DefaultThresholdValue = 0.0m,
                            Description = "High water cut combined with low oil production",
                            Name = "Combined Production Deficit",
                            Severity = "Critical",
                            TargetWellType = "PROD"
                        },
                        new
                        {
                            RuleCode = "RULE_LOW_INJECTION",
                            DefaultThresholdValue = 1000.0m,
                            Description = "Injector falls below target injection rate",
                            Name = "Low Injection Rate",
                            Severity = "Warning",
                            TargetWellType = "INJ"
                        },
                        new
                        {
                            RuleCode = "RULE_HIGH_PRESSURE",
                            DefaultThresholdValue = 2500.0m,
                            Description = "Injection pressure exceeds maximum allowed",
                            Name = "High Injection Pressure",
                            Severity = "Critical",
                            TargetWellType = "INJ"
                        },
                        new
                        {
                            RuleCode = "RULE_INACTIVE_WELL",
                            DefaultThresholdValue = 0.0m,
                            Description = "Well is shut-in or under maintenance",
                            Name = "Inactive Well",
                            Severity = "Notice",
                            TargetWellType = "ANY"
                        });
                });

            modelBuilder.Entity("ZSK.Services.ReferenceData.Entities.ZskRefRelationshipStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("ZSK_Ref_RelationshipStatus");

                    b.HasData(
                        new
                        {
                            Code = "ACT",
                            Description = "Injector-producer relationship is active",
                            Name = "Active"
                        },
                        new
                        {
                            Code = "INA",
                            Description = "Injector-producer relationship is inactive",
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("ZSK.Services.ReferenceData.Entities.ZskRefWellStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("ZSK_Ref_WellStatus");

                    b.HasData(
                        new
                        {
                            Code = "ACT",
                            ColorCode = "#28a745",
                            Description = "Well is actively operating",
                            Name = "Active"
                        },
                        new
                        {
                            Code = "SHT",
                            ColorCode = "#dc3545",
                            Description = "Well is temporarily shut in",
                            Name = "Shut-in"
                        },
                        new
                        {
                            Code = "MNT",
                            ColorCode = "#ffc107",
                            Description = "Well is under maintenance",
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("ZSK.Services.ReferenceData.Entities.ZskRefWellType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("ZSK_Ref_WellType");

                    b.HasData(
                        new
                        {
                            Code = "INJ",
                            Description = "Water injection well",
                            Name = "Injector"
                        },
                        new
                        {
                            Code = "PROD",
                            Description = "Fluid production well",
                            Name = "Producer"
                        });
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Domain.Entities.InjectorProducerRelationship", b =>
                {
                    b.HasOne("BackEndWaterFloodApp.Domain.Entities.WaterfloodRecord", "InjectorWell")
                        .WithMany()
                        .HasForeignKey("InjectorWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEndWaterFloodApp.Domain.Entities.WaterfloodRecord", "ProducerWell")
                        .WithMany()
                        .HasForeignKey("ProducerWellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZSK.Services.ReferenceData.Entities.ZskRefRelationshipStatus", "RelationshipStatus")
                        .WithMany()
                        .HasForeignKey("RelationshipStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InjectorWell");

                    b.Navigation("ProducerWell");

                    b.Navigation("RelationshipStatus");
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Domain.Entities.WaterfloodRecord", b =>
                {
                    b.HasOne("ZSK.Services.ReferenceData.Entities.ZskRefWellStatus", "WellStatus")
                        .WithMany()
                        .HasForeignKey("WellStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZSK.Services.ReferenceData.Entities.ZskRefWellType", "WellType")
                        .WithMany()
                        .HasForeignKey("WellTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WellStatus");

                    b.Navigation("WellType");
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Models.UserRole", b =>
                {
                    b.HasOne("BackEndWaterFloodApp.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndWaterFloodApp.Models.zsk.zRole", "zRole")
                        .WithMany()
                        .HasForeignKey("zRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("zRole");
                });

            modelBuilder.Entity("BackEndWaterFloodApp.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
